/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import Classes.DataEngine;
import Classes.Director;
import Interfaces.DataBluePrint;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Pouya
 */
public class RoomManagement extends Director implements DataBluePrint {
        DataEngine RoomData = new DataEngine("RoomList.txt");
        DataEngine RoomClass = new DataEngine("RoomClass.txt");
        List<String[]> Classes;
    /**
     * Creates new form UserManagement
     */
    public RoomManagement() {
        initComponents();
        Classes = RoomClass.ReadFile();
        CClass.addItem("Room Type");
        CClass.removeAllItems();
        for (String[] s : Classes ) {
            CClass.addItem(s[0].split("\\.")[1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CClass = new javax.swing.JComboBox();
        TID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RAdd = new javax.swing.JRadioButton();
        RRemove = new javax.swing.JRadioButton();
        RUpdate = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Management");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(71, 61, 87));

        jButton1.setBackground(new java.awt.Color(148, 143, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Apply");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CClass.setBackground(new java.awt.Color(148, 143, 153));
        CClass.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Room Type" }));

        TID.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TID.setText("Room Number");
        TID.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(71, 61, 87));
        jPanel2.setLayout(null);

        buttonGroup1.add(RAdd);
        RAdd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        RAdd.setForeground(new java.awt.Color(255, 255, 255));
        RAdd.setText("Add");
        RAdd.setOpaque(false);
        RAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAddActionPerformed(evt);
            }
        });
        jPanel2.add(RAdd);
        RAdd.setBounds(10, 8, 45, 21);

        buttonGroup1.add(RRemove);
        RRemove.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        RRemove.setForeground(new java.awt.Color(255, 255, 255));
        RRemove.setText("Remove");
        RRemove.setOpaque(false);
        RRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(RRemove);
        RRemove.setBounds(64, 8, 70, 21);

        buttonGroup1.add(RUpdate);
        RUpdate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        RUpdate.setForeground(new java.awt.Color(255, 255, 255));
        RUpdate.setText("Update");
        RUpdate.setOpaque(false);
        RUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(RUpdate);
        RUpdate.setBounds(138, 8, 57, 21);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(8, 6, 192, 28);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CClass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (RAdd.isSelected()) {
            Add();
        }
        else if (RRemove.isSelected()) {
            Delete();
        }
        else if (RUpdate.isSelected()) {
            if (Delete() == true) {
                Add();                
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please Select An Option.");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAddActionPerformed

        Activate (TID, CClass);
// TODO add your handling code here:
    }//GEN-LAST:event_RAddActionPerformed

    private void RRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRemoveActionPerformed
        DeActivate(CClass);
// TODO add your handling code here:
    }//GEN-LAST:event_RRemoveActionPerformed

    private void RUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUpdateActionPerformed
        Activate (TID, CClass);
        // TODO add your handling code here:
    }//GEN-LAST:event_RUpdateActionPerformed
        @Override
        public void Add () {
            Boolean validation = IntValidation (TID.getText()) & CClass.getSelectedIndex() > 0;
            if (validation == true) {
                StringBuilder sb = new StringBuilder();
                sb.append("RoomNumber.").append(TID.getText()).append("\t");
                if (RoomData.Validate(sb.toString()) == false) {
                sb.append("Class.").append(CClass.getSelectedItem().toString()).append("\t");
                RoomData.Append(sb.toString());
                JOptionPane.showMessageDialog(null, "Database Updated Successfully");                
                }
                else {
                    JOptionPane.showMessageDialog(null, "The Exact Same Roon Number Exists In The System DataBase.");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "An Error Occured Due To One Of These Reasons:\n1- The Room Number Must Be An Integer\n2- You Must Select A Value From The Combo Box.");
            }
}
        @Override
        public void Add (String ID) {

        }
        @Override
        public Boolean Delete () {
            if (RoomData.Validate("RoomNumber."+TID.getText())) {
                RoomData.Delete("RoomNumber."+TID.getText());
                JOptionPane.showMessageDialog(null, "Database Updated Successfully");                
                return true;
            }
            else {
                JOptionPane.showMessageDialog(null, "The Entered Room Number Was Not Found.");
                return false;
            }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CClass;
    private javax.swing.JRadioButton RAdd;
    private javax.swing.JRadioButton RRemove;
    private javax.swing.JRadioButton RUpdate;
    private javax.swing.JTextField TID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
